version: "3.9"

services:
  backend:
    build: .
    container_name: catalog-backend
    command: >
      sh -c "python manage.py migrate &&
             gunicorn --workers 4 --bind 0.0.0.0:9001 main.wsgi:application"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9001:9001"
    volumes:
      - .:/app
    env_file:
      - config.env
    networks:
      - shared-net



networks:
  shared-net:
    external: true